version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: swd392_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: