server:
  port: 8080

spring:
  application:
    name: SWD392
  profiles:
    active: local
  datasource:
    # URL của Postgres (cần tạo DB trước)
    url: jdbc:postgresql://localhost:5432/swd392_db
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          # Quan trọng: Dialect cho Postgres
          dialect: org.hibernate.dialect.PostgreSQLDialect
          # Format SQL cho dễ đọc
          format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    # Ep Swagger UI su dung dung duong dan config
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours in milliseconds


