server:
  port: 8080

spring:
  application:
    name: SWD392
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://avnadmin:AVNS_KIMU-8BkaoiwkfLS0nI@mysql-b96f9c6-minkoi0408-f654.f.aivencloud.com:21012/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_KIMU-8BkaoiwkfLS0nI
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    # Ep Swagger UI su dung dung duong dan config
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours in milliseconds


